# Make a logo with your name and year of birth and ig name all enclosed in a box
print(" ================================================= ")
print("|                                                 |")
print("|    We present...                                |")
print("|                                                 |")
print("|                DOKJA       KIM                  |")
print("|                                                 |")
print("|           Amazing   Daring    Kind :)           |")
print("|                                                 |")
print("|            Since 2004                           |")
print("|                                                 |")
print("|            @dark_.lilac                         |")
print("|                                                 |") 
print(" ================================================= ")